import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LLMProvider } from "@/contexts/LLMContext";
import { QueryProvider } from "@/contexts/QueryContext";
import { CompletionProvider } from "@/contexts/CompletionContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "chatSQL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LLMProvider>
          <QueryProvider>
            <CompletionProvider>
              {children}
            </CompletionProvider>
          </QueryProvider>
        </LLMProvider>
      </body>
    </html>
  );
}
