import { Providers } from "@/components/common/Providers";
import "./globals.css";

export const metadata = {
  title: "ChatSQL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='zh-CN'>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
